config/routes.rb
Rails.application.routes.draw do

  root 'pages#home',as: :home
  get '/about' => 'about#about', as: :about

  get '/contact' => 'contact#contact', as: :contact

  get '/product' => 'product#product', as: :product

  get '/news' => 'news#news', as: :news

  

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
 
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def home
  end

  def contact
  end

  def product
  end

  def news
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact/contact.html.erb
  <!-- BEGIN MENU -->
  <section id="menu-area">      
    <nav class="navbar navbar-default" role="navigation">  
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- LOGO -->              
          <!-- TEXT BASED LOGO -->

          <!-- IMG BASED LOGO  -->
            <a class="navbar-brand" href="index.html"><img src="..//images/logo.jpg" alt="logo"></a> 
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav navbar-right main-nav">
           <li><%=link_to "Trang Chủ", home_path()%></li>
            <li><%= link_to "Giới Thiệu", about_path()%></li>
            <li><%= link_to "Sản Phẩm", product_path()%></li>
            <li><%= link_to "Tin Tức", news_path()%></li>
            <li  class="active"><%= link_to "Liên Hệ", contact_path()%></li>

            
          </ul>                     
        </div><!--/.nav-collapse -->
        <a href="#" id="search-icon">
          <i class="fa fa-search">            
          </i>
        </a>
      </div>     
    </nav>
  </section>
  <!-- END MENU --> 
      <section id="contact">
     <div class="container">
       <div class="row">
         <div class="col-md-12">
           <div class="title-area">
              <h2 class="title">Liên hệ với chúng tôi</h2>
              <span class="line"></span>
              <p>Là phân phối sản phẩm đá viên – nước đá tinh khiết lớn nhất của hệ thống nhà máy nước đá Đông An Bình với hơn 10 năm kinh nghiệm, là một trong những nhà phân phối nước đá uy tín hàng đầu tại Tp.HCM</p>
            </div>
         </div>
         <div class="col-md-12">
           <div class="cotact-area">
             <div class="row">
               <div class="col-md-4">
                 <div class="contact-area-left">
                   <h4>Thông tin liên lạc</h4>
                   <p> Khách hàng mới khi đến với chúng tôi sẽ được tài trợ 100% tất cả các thiết bị, cùng với những ưu đãi đặc biệt về giá cả.</p>
                   <address class="single-address">
                     <p>Địa chỉ: 15 đường Linh Đông, Quận Thủ Đức, TP. HCM</p>
                     <p>tranbinhfc@gmail.com</p>
                     <p>+(84)1649102011 </p>
                   </address> 
                   <div class="footer-right contact-social">
                      <a href="index.html"><i class="fa fa-facebook"></i></a>
                      <a href="#"><i class="fa fa-twitter"></i></a>
                      <a href="#"><i class="fa fa-google-plus"></i></a>
                      <a href="#"><i class="fa fa-linkedin"></i></a>
                      <a href="#"><i class="fa fa-pinterest"></i></a>
                    </div>                
                 </div>
               </div>
               <div class="col-md-8">
                 <div class="contact-area-right">
                   <form action="" class="comments-form contact-form">
                    <div class="form-group">                        
                      <input type="text" class="form-control" placeholder="Tên của bạn ...">
                    </div>
                    <div class="form-group">                        
                      <input type="email" class="form-control" placeholder="Email của bạn ...">
                    </div>
                     <div class="form-group">                        
                      <input type="text" class="form-control" placeholder="Tiêu dề ...">
                    </div>
                    <div class="form-group">                        
                      <textarea placeholder="Nội dung ..." rows="3" class="form-control"></textarea>
                    </div>
                    <button class="comment-btn">Gửi Thông Điệp</button>
                  </form>
                 </div>
               </div>
             </div>
           </div>
         </div>
       </div>
     </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nuoc Da Tinh Khiet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Font Awesome -->
    <link href="assets/stylesheets/font-awesome.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="assets/stylesheets/bootstrap.css" rel="stylesheet">    
    <!-- Slick slider -->
    <link rel="stylesheet" type="text/css" href="assets/stylesheets/slick.css"/> 
    <!-- Fancybox slider -->
    
    <link rel="stylesheet" href="assets/stylesheets/jquery.fancybox.css" type="text/css" media="screen" /> 
    <!-- Animate css -->
    <link rel="stylesheet" type="text/css" href="assets/stylesheets/animate.css"/> 
    <!-- Progress bar  -->
    <link rel="stylesheet" type="text/css" href="assets/stylesheets/bootstrap-progressbar-3.3.4.css"/> 
     <!-- Theme color -->
    <link id="switcher" href="assets/stylesheets/theme-color/default-theme.css" rel="stylesheet">

    <!-- Main Style -->
    <link href="assets/stylesheets/style.css" rel="stylesheet">

    <!-- Fonts -->

    <!-- Open Sans for body font -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <!-- Lato for Title -->
    <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>    
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <!-- BEGAIN PRELOADER -->
  <div id="preloader">
    <div id="status"><img src="..//images/loader.gif" alt=""></div>
  </div>
  <!-- END PRELOADER -->

  <!-- SCROLL TOP BUTTON -->
  <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->

  <!-- Start header -->
  <header id="header">
    <!-- header top search -->
    <div class="header-top">
      <div class="container">
        <form action="">
          <div id="search">
          <input type="text" placeholder="Tìm kiếm sản phẩm bạn muốn..." name="s" id="m_search" style="display: inline-block;">
          <button type="submit">
            <i class="fa fa-search"></i>
          </button>
        </div>
        </form>
      </div>
    </div>
    <!-- header bottom -->
    <div class="header-bottom">
      <div class="container">
        <div class="row">
         
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="header-login">
              <a class="login modal-form" data-target="#login-form" data-toggle="modal" href="#">Đăng Nhập / Đăng Ký</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- End header -->
  
  <!-- Start login modal window -->
  <div aria-hidden="false" role="dialog" tabindex="-1" id="login-form" class="modal leread-modal fade in">
    <div class="modal-dialog">
      <!-- Start login section -->
      <div id="login-content" class="modal-content">
        <div class="modal-header">
          <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
          <h4 class="modal-title"><i class="fa fa-unlock-alt"></i>Đăng Nhập</h4>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <input type="text" placeholder="User name" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
             <div class="loginbox">
              <label><input type="checkbox"><span>Ghi Nhớ Tài Khoản</span></label>
              <button class="btn signin-btn" type="button">Đăng Nhập</button>
            </div>                    
          </form>
        </div>
        <div class="modal-footer footer-box">
          <a href="#">Quên mật khẩu?</a>
          <span>Không tài khoản ? <a id="signup-btn" href="#">Đăng Ký.</a></span>            
        </div>
      </div>
      <!-- Start signup section -->
      <div id="signup-content" class="modal-content">
        <div class="modal-header">
          <button aria-label="Close" data-dismiss="modal" class="close" type="button"><span aria-hidden="true">×</span></button>
          <h4 class="modal-title"><i class="fa fa-lock"></i>Sign Up</h4>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <input placeholder="Name" class="form-control">
            </div>
            <div class="form-group">
              <input placeholder="Username" class="form-control">
            </div>
            <div class="form-group">
              <input placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <div class="signupbox">
              <span>Đã có tài khoản? <a id="login-btn" href="#">Đăng Nhập.</a></span>
            </div>
            <div class="loginbox">
              <label><input type="checkbox"><span>Ghi nhớ tài khoản</span><i class="fa"></i></label>
              <button class="btn signin-btn" type="button">Đăng Ký</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- End login modal window -->

  
  
<%= yield %>
 <!-- Start footer -->
  <footer id="footer">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-sm-6">
          <div class="footer-left">
            <p>Designed by <a href="#">Trần Bình</a>@2016</p>
          </div>
        </div>
        <div class="col-md-6 col-sm-6">
          <div class="footer-right">
            <a href="index.html"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-google-plus"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest"></i></a>
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- End footer -->

</body>
</html>